# To run: conda env create -f environment.yml
name: spt
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - alsa-lib=1.2.8
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - attr=2.5.1
  - attrs=22.1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=39.0.1
  - cudatoolkit=11.0.3
  - cudnn=8.4.1.50
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.5.0
  - fftw=3.3.10
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gast=0.5.3
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpc-cpp=1.45.2
  - grpcio=1.45.0
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - h5py=3.7.0
  - harfbuzz=6.0.0
  - hdf5=1.10.6
  - icu=70.1
  - idna=3.4
  - importlib-metadata=4.11.3
  - jack=1.9.22
  - jpeg=9e
  - keras=2.8.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libprotobuf=3.20.3
  - libsndfile=1.2.0
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mpg123=1.31.3
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nccl=2.14.3.1
  - ncurses=6.4
  - nspr=4.35
  - nss=3.89
  - numpy=1.21.6
  - oauthlib=3.2.1
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - packaging=22.0
  - pcre2=10.40
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - ply=3.11
  - protobuf=3.20.3
  - pulseaudio=16.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.7
  - pyyaml=6.0
  - qt-main=5.15.6
  - re2=2022.06.01
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.7.3
  - setuptools=65.6.3
  - sip=6.7.2
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.1
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.8.1
  - tensorflow-base=2.8.1
  - tensorflow-estimator=2.8.1
  - termcolor=2.1.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - werkzeug=2.2.2
  - wheel=0.38.4
  - wrapt=1.14.1
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - yaml=0.2.5
  - yarl=1.8.1
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.4
